CREATE TABLE User (
UserID INTEGER,
UserName VARCHAR(50) NOT NULL,
BirthDATE DATE,
StartingWeight INTEGER NOT NULL,
Height INTEGER,
Country VARCHAR(50),
ZipCode CHAR(10),
JoinDate DATE,
CONSTRAINT UserPK PRIMARY KEY(UserID));

CREATE TABLE Exercise (
ExerciseID INTEGER NOT NULL,
ExerciseDesc varCHAR(50) NOT NULL,
ExerciseType varCHAR(50) NOT NULL,
CalBurnedPerMin INTEGER NOT NULL,
CONSTRAINT ExercisePK PRIMARY KEY(ExerciseID));

CREATE TABLE WaterLog (
WaterLogID INTEGER NOT NULL,
UserID INTEGER NOT NULL,
DATE DATE NOT NULL,
NoOfCups INTEGER NOT NULL,
CONSTRAINT WaterLogPK PRIMARY KEY(WaterLogID),
FOREIGN KEY(UserID) REFERENCES User(UserID)); 

Create table Food 
( 
FoodID INTEGER, 
FoodName VARCHAR(50), 
FoodCalories INTEGER, 
Protein INTEGER, 
Fat INTEGER, 
Carbs INTEGER, 
ServingSize CHAR(10),
CONSTRAINT FoodPK PRIMARY KEY(FoodID)); 

CREATE TABLE Goals (
GoalID INTEGER,
GoalType varCHAR(50),
GoalLevel varCHAR(50),
StartWeightLimit INTEGER,
EndWeightLimit INTEGER,
DailyCalorieLimit INTEGER,
WeeklyWeightGainOrLoss INTEGER,
CONSTRAINT GoalsPK PRIMARY KEY(GoalID)); 

CREATE TABLE GoalLog
(
GoalLogID INTEGER,
UserID INTEGER,
GoalID INTEGER,
GoalLogDate DATE NOT NULL,
Goal_Weight Integer NOT NULL
CONSTRAINT GoalLogPK PRIMARY KEY(GoalLogID),
FOREIGN KEY(UserID) REFERENCES User(UserID),
FOREIGN KEY(GoalID) REFERENCES Goals(GoalID)
);


CREATE TABLE ExerciseLog (
ExerciseLogID INTEGER,
UserID INTEGER NOT NULL,
ExerciseID INTEGER NOT NULL,
Duration INTEGER NOT NULL,
ExLogDATE DATE NOT NULL,
CONSTRAINT ExercisePK PRIMARY KEY(ExerciseLogID),
FOREIGN KEY(UserID) REFERENCES User(UserID),
FOREIGN KEY(ExerciseID) REFERENCES Exercise(ExerciseID)); 


CREATE TABLE FoodLog 
( 
FoodLogID INTEGER,
FoodID INTEGER, 
UserID INTEGER, 
FoodLogDate DATE NOT NULL, 
TypeOfMeal CHAR(20), 
NoOfServing INTEGER, 
CONSTRAINT FoodLogPK PRIMARY KEY(FoodLogID),
FOREIGN KEY(UserID) REFERENCES User(UserID),
FOREIGN KEY(FoodID) REFERENCES Food(FoodID)); 
 
 
 
CREATE TABLE WeightLog 
( 
WeightLogID INTEGER,
UserID INTEGER, 
Weight INTEGER, 
WeightLogDate DATE NOT NULL,
CONSTRAINT WeightLogPK PRIMARY KEY(WeightLogID),
CONSTRAINT UserFK FOREIGN KEY(UserID) REFERENCES User(UserID)); 


CREATE TABLE FriendList (
Initiator INTEGER NOT NULL,
Acceptor INTEGER NOT NULL,
DATE DATE,
Chat_Box_Link VARCHAR(50),
CONSTRAINT FriendListPK PRIMARY KEY(initiator,acceptor),
FOREIGN KEY(Initiator) REFERENCES User(UserID),
FOREIGN KEY(Acceptor) REFERENCES User(UserID));


CREATE TABLE Challanges (
ChallangeID INTEGER,
Challanger INTEGER,
Opponent INTEGER,
StartDATE DATE,
EndDATE DATE,
CONSTRAINT ChallangesPK PRIMARY KEY(ChallangeID),
FOREIGN KEY(Challanger) REFERENCES FriendList(Initiator),
FOREIGN KEY(Opponent) REFERENCES FriendList(acceptor));


CREATE TABLE Trainer (
TrainerID INTEGER,
First_Name VARCHAR(50),
Last_Name VARCHAR(50),
YearsOfExp INTEGER,
Expertise VARCHAR(50),
PricePerCustomer Integer,
CONSTRAINT TrainerPK PRIMARY KEY(TrainerID)
);


CREATE TABLE USER_TRAINER (
USER_TRAINER_ID INTEGER,
UserID INTEGER,
TrainerID INTEGER,
StartDATE DATE,
EndDATE DATE,
CONSTRAINT UserTrainerPK PRIMARY KEY(USER_TRAINER_ID),
FOREIGN KEY(UserID) REFERENCES User(UserID),
FOREIGN KEY(TrainerID) REFERENCES Trainer(TrainerID)
);